### ISSUE TITLE
[&#xE720;] "Microphone" Bug

### ISSUE THREAD

**Issue by seboschtion** [Templarian/ModernIcons#12]
There are two more microphones:
&#xEC54; (mute?)
&#xEC55; (quiet hours?)
&#xEC56; (broken?)

**Comment by Templarian** [comment]
That's very odd. It looks like the MSDN page is missing a lot of icons that are in the font (seeing a lot of others not in there also). looks like if there is no enum they simply don't list it.

https://msdn.microsoft.com/en-us/library/windows/apps/jj841126.aspx

**Comment by seboschtion** [comment]
It is and it is not: "Also, keep in mind that the Segoe MDL2 Assets font includes many more icons than we can show here. Many of these are intended for specialized purposed and are not typically used anywhere else." (Directly over the heart table).

The Character Map on Windows shows all icons. There are a lot more. If you want I can help you to complete the collection, but the code does not seem to be open?

**Comment by Templarian** [comment]
If you click the checkbox on the top right it lists out all the legacy / duplicate icons. I've marked any icons not on that MSDN page as a duplicate. So really I just need the 4 digit hex code for the ones that need to be included.

The source code is actually just a hard coded html page (so right click view source, this was a very messy quick idea for myself that ended up being useful so I put it online).

I do need to grab the latest Segoe MDL2 font and convert it to woff / woff2 for the site.

I'm working on a 3rd party collection of these icons + tons of custom open source ones in the same style (that is what modernicons.io is for).

**Comment by seboschtion** [comment]
Oooh, I did not see that, sorry!
The hex code are EC54, EC55 and EC56, in the same order as listed above.

Looking forward to your collection!
