### ISSUE TITLE
Asset Codes look shifted in firefox

### ISSUE THREAD

**Issue by arijosino** [Templarian/ModernIcons#13]
The codes referring  to the assets appear to be shifted down (they appear outside the div)
if you put them inside a <span></span>, they will get back inside their respective <div>
![segoemdl2assetscheatsheet_shiftedcodes](https://cloud.githubusercontent.com/assets/2459836/10613326/08162916-772b-11e5-8839-36d4e2dddca5.png)

**Comment by Templarian** [comment]
Fixed. Forgot to close this issue.
