### ISSUE TITLE
[&#xE133;] "" Bug

### ISSUE THREAD

**Issue by mikegoatly** [Templarian/ModernIcons#15]
I don't think this is a duplicate - it's not on the official MSDN pages, but it is very similar to the "enter selection mode" icon in the Mail app.

**Comment by Templarian** [comment]
Thanks... yea, tbh. I'm not sure what to do with these that aren't shown on the official list.

I get that they exist in the official font file, but I'm not sure if developers are suppose to use them since they are not clearly documented.

I've made it visible and added a keyword of `undocumented`.

**Comment by mikegoatly** [comment]
No problem - "undocumented" is probably a good approach to this.
