### ISSUE TITLE
[&#xE2F6;] "" Bug

### ISSUE THREAD

**Issue by rubenvb** [Templarian/ModernIcons#18]
What icon is this one a duplicate of exactly?

**Comment by Templarian** [comment]
Good question. The list is actually taken from... https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/segoe-ui-symbol-font

Will get that figured out shortly, right now focus is going into Modern Icons which will create a easier to use version of the MDL2 icons.
