### ISSUE TITLE
License Terms

### ISSUE THREAD

**Issue by softwaremagico** [Templarian/ModernIcons#3]
HI Andrew! 

I am developing an application (released as free software soon) and your icons fits very well with it. In some cases I would need some extra icons, and merging two icons is enough to me (i,e. adding and remove an object is an icon with an extra plus or minus) therefore making a request for this seems unnecessary. But theoretically, this would be a derived work. In your license.txt seems that is not allowed to do this and in github there is no much information available to it.

It would not be a problem to share these "new" icons with you, and maybe with this contribution there would not be any problem with the license, but I am not a designer and I am almost sure that the quality is not so good in all of them. Therefore I am not sure if I can use your icon set or I need to look for another set with a different license restriction. 

An example of the changes is this icon as "webservice": 

![webservice](https://cloud.githubusercontent.com/assets/6171537/8352602/c0a2463c-1b36-11e5-84ca-634ee2a93db1.png)

As you can see is the merge with two icons. I have more ideas like this one.

**Comment by Templarian** [comment]
Actually eventually the site will offer the ability to do this (subfont + custom glyphs). The icon you shared does not match the Material Design Icons system icon guidelines, but if you submit new issues for your various icon requests (with your icons as a reference) they will slowly get added into the pack.

I've included `v1.1.34` at https://fonticons.com/ which can generate subfonts + custom glyphs. But there are other services that allow this also.

Don't worry about modifying the webfont with additional icons. A fancy license page will be coming soon that explains that this is perfectly fine. It will require a link back in the open source project's license file (and optional link back in the readme for the repo).

**Comment by Templarian** [comment]
Dang, I just noticed this was for Modern UI Icons. Sorry, completely thought it was for Material Design Icons.

Ignore what I said. You have my permission to make a derived set. Link back in the readme/license is all that is required.

I'm not taking additional icons for this set at this time until it is in the new icon platform.

**Comment by softwaremagico** [comment]
Ok, thanks. My fault to not point that are Modern Icons, your probably have lot of icons packets. There is not problem to include the licence file and to link you in my project. This is the usual way.

**Comment by Templarian** [comment]
For reference: https://github.com/Templarian/WindowsIcons/

That is the correct repo for that site. This repo is for v2 (renamed to Modern Icons). Dropped the UI from the name.
