### ISSUE TITLE
Can I use these icons legally?

### ISSUE THREAD

**Issue by Maxim-Mazurok** [Templarian/ModernIcons#39]
I want to use these icons on my website, are they legal to use?

Microsoft seems to prohibit reverse-engineering and converting these icons. So, it looks like there's no way I can get them to work on mac/linux and older windows systems, without this font installed.

https://social.msdn.microsoft.com/Forums/en-US/6ed19850-f0fc-49c0-8155-8b0101c43c0c/use-windows-10-segoe-mdl2-assets-font-in-web-development?forum=windowscompatibility

https://docs.microsoft.com/en-us/typography/fonts/font-faq#web

**Comment by Templarian** [comment]
This project was abandoned 5 years ago. I think they offer these in a package now, search around.

**Comment by Templarian** [comment]
I'll delete this repo this weekend to clear up any confusion. Forgot it still was here.

**Comment by Maxim-Mazurok** [comment]
I think MS doesn't offer to license this font, it's only available as an embedded font in windows.
Here's the closest thing that I've found, but it seems like they have much fewer icons: https://github.com/microsoft/fonts

Thanks for your quick response, BTW, I've found this repo from this website: http://modernicons.io/segoe-mdl2/cheatsheet/

**Comment by Templarian** [comment]
I let that domain expire after remembering I owned it a few months ago. 😅 Should stop working shortly.

I maintain https://github.com/Templarian/MaterialDesign now, but we have a light version: https://github.com/Templarian/MaterialDesignLight (but it's a small subset so far).
