### ISSUE TITLE
Cell Phone Status Icon Name Suggestions

### ISSUE THREAD

**Issue by TwelveBaud** [Templarian/ModernIcons#9]
&#xE875; - SIM blocked (i.e. stolen phone)
&#xE876; - SIM missing
&#xE877; - Vibrate
&#xE878; - Roaming 1
&#xE879; - Roaming 2
&#xE87A; - Forwarded Roaming 1
&#xE87B; - Forwarded Roaming 2
&#xE880; - Forwarded
&#xE881; - Forwarded, SIM locked (i.e. need passcode)
&#xE882; - SIM # 2 (for phones with two SIM slots, i.e. China)
&#xE883; - SIM # 2 locked
&#xE884; - SIM # 1
&#xE885; - SIM # 1 locked
&#xE886; - Cellular
&#xE887; - Cellular in-call
&#xE888; - Cellular locked
&#xE889; - Generic locked

![mdl2mod](https://cloud.githubusercontent.com/assets/1701040/9610419/61060e92-50a7-11e5-83a0-9f3a5a16a22d.png)

**Comment by Templarian** [comment]
@TwelveBaud Those show up as missing glyphs, best to use images or a screenshot of the above.

**Comment by TwelveBaud** [comment]
Edited a copy of the Segoe MDL2 cheatsheet and pasted a screenshot

**Comment by Templarian** [comment]
Thanks, I'll get these updated tonight.
